//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int item_id { get; set; }
        public int list_id { get; set; }
        public int category_id { get; set; }
        public string taskName { get; set; }
        public bool isDone { get; set; }
        public System.DateTime lastChangedDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual TodoList TodoList { get; set; }
    }
}
